### ISSUE TITLE
Noggenfogger Elixir effect may disable AA

### ISSUE THREAD

**Issue by Si1ker** [azerothcore/azerothcore-wotlk#11719]
Originally reported by Sílker at https://github.com/chromiecraft/chromiecraft/issues/3495

### Current Behaviour

Noggenfogger has **the chance** to disable auto-attacks.

When you drink [Noggenfogger Elixir](https://classic.wowhead.com/item=8529/noggenfogger-elixir) you have the chance to get one of the following three effects:

[You feel light](https://classic.wowhead.com/spell=16593/noggenfogger-elixir)
[You feel smaller](https://classic.wowhead.com/spell=16595/noggenfogger-elixir)
[You've stopped breathing](https://classic.wowhead.com/spell=16591/noggenfogger-elixir)

The third one, once you turn into a skeleton, has a low-rate bug (it is not a 100% reproducible bug), it may disable your auto-attacks until you log back into the game. For personal testing, I'd say a 20% repro-rate.

The [first](https://classic.wowhead.com/spell=16593/noggenfogger-elixir) and [second](https://classic.wowhead.com/spell=16595/noggenfogger-elixir) effects have not triggered this bug in 100 tests. Only the [third](https://classic.wowhead.com/spell=16591/noggenfogger-elixir) one.

Note:  **/startattack** , does not work when you're affected by the bug.

Tested in chromiecraft after latest update 5/11 on [c7f74e5](https://github.com/chromiecraft/azerothcore-wotlk/commit/c7f74e563758241e29721e95b86aed0093a8856a)

https://user-images.githubusercontent.com/61223313/167906947-a5cd84e4-f623-4c99-8b04-c173ac0b9eb4.mp4

### Expected Blizzlike Behaviour

[You've stopped breathing - Aura 16591](https://classic.wowhead.com/spell=16591/noggenfogger-elixir) shouldn't have the chance to disable your auto-attacks

### Source

Is not planned for an esthetic potion to break your gameplay

### Steps to reproduce the problem

.add 8529 100

Drink 'till you get the aura 16591 -> try AA to a target
Were you able to attack?
- Yes -> repeat again.
- No -> found the bug.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/c7f74e563758241e29721e95b86aed0093a8856a

### Operating system

Ubuntu 20.04

### Custom changes or Modules

N/A

**Comment by UltraNix** [comment]
@Si1ker Still a bug? I remember I fixed something very similar bug.

**Comment by Si1ker** [comment]
> @Si1ker Still a bug? I remember I fixed something very similar bug.

@UltraNix  As far as I know, yes it's still present in fresh acores

**Comment by UltraNix** [comment]
Tried with 100 elixirs - no bug.

**Comment by Si1ker** [comment]
Thanks for the input @UltraNix  will close and reopen if I ever heard about it again.

**Comment by Never6** [comment]
this is still an issue btw, would appreciate if this got reopened

**Comment by Never6** [comment]
> Tried with 100 elixirs - no bug.


test better then

**Comment by heyitsbench** [comment]
Consistent reproduction steps found. Make a macro with the following:
```
/use Noggenfogger Elixir
/use Noggenfogger Elixir
/use Noggenfogger Elixir
/use Noggenfogger Elixir
/use Noggenfogger Elixir
/use Noggenfogger Elixir
/use Noggenfogger Elixir
/use Noggenfogger Elixir
/use Noggenfogger Elixir
.additem 8529 50
```
Use `.cheat cooldown`, get into combat with a mob, cast an uber heal spell on it, and start using the macro (no need to spam).

**Comment by heyitsbench** [comment]
I have tested it a little bit, the client does not seem to be sending the start swing packet once this bug takes effect, so it's not like the core is getting caught up in some bad evaluations for that process like I suspected at a glance.

**Comment by heyitsbench** [comment]
This still seems to be an issue, tested by Jedbouk on the CC Discord server.
