### ISSUE TITLE
 judgment only does 1 damage 

### ISSUE THREAD

**Issue by BeefSteaker** [azerothcore/azerothcore-wotlk#13331]
https://github.com/chromiecraft/chromiecraft/issues/4159 confirmed on live/local
### Current Behaviour

During one of the two active seals (wisdom or light) the judgment spells (wisdom/justice/light) do only 1 damage (see 2 in critical hit). However, the seal of piety does correct damage.

https://youtu.be/AtEYRI4MDSc
https://youtu.be/vbyChxRkoO4

Lors d'un des deux sceaux d'actifs (sagesse ou lumière) les sorts de jugements (sagesse/justice/lumière) ne font que 1 de dégât (voir 2 en coup critique). Or le sceau de piété fait des dégâts corrects.

### Expected Blizzlike Behaviour

Judgments damage should be greater than 1

Les dégâts des jugements devraient être supérieur à 1

### Source

Previous closed issue issue https://github.com/chromiecraft/chromiecraft/issues/4123

### Steps to reproduce the problem

.learn 20185
.learn 20186
.additem 41092
learn glyph

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/77faa1d84d85199170ef540a43b5ed824de43702

### Operating system

Ubuntu 20.04

### Custom changes or Modules

[mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
    [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
    [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
    [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
    [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
    [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
    [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
    [mod-dmf-switch](https://github.com/azerothcore/mod-dmf-switch)
    [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
    [mod-eluna](https://github.com/azerothcore/mod-eluna)
    [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
    [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
    [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
    [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
    [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
    [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
    [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
    [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
    [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
    [mod-transmog](https://github.com/azerothcore/mod-transmog)
    [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
    [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
    [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
    [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
    [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
    [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
    [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
    [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
    [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
    [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
    [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

**Comment by Gultask** [comment]
I thought it was fixed by: https://github.com/azerothcore/azerothcore-wotlk/pull/13104
Regression?

**Comment by BeefSteaker** [comment]
still happening yes. seems to only apply to seal of light and seal of wisdom
