### ISSUE TITLE
[RAID] Temple of Ahn'Qiraj (Boss Ouro Doesn't Spawn)

### ISSUE THREAD

**Issue by gtao725** [azerothcore/azerothcore-wotlk#1689]
##### SMALL DESCRIPTION:

The optional boss Ouro in AQ40 raid never spawns correctly. So unable to fight it at all.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

https://www.youtube.com/watch?v=uGhW2pvRKA4
https://wow.gamepedia.com/Ouro

##### CURRENT BEHAVIOUR:

You see the boss move around underground but it never emerges from the sand.

##### STEPS TO REPRODUCE THE PROBLEM:

1. .tele aq40
2. fight up to location #8 on the following map:
![image](https://user-images.githubusercontent.com/35093669/55638215-4190e980-57f9-11e9-87eb-3620a7c16439.png)
3. You see the boss move around underground and once you are in range, it attacks you, but this is completely wrong. The boss should emerge from the sand and then attack the raid party.

##### BRANCH(ES):

master

##### AC HASH/COMMIT:

9eb6e9a

##### OPERATING SYSTEM:

Win 7/10/Svr 2016

##### MODULES:

N/A

##### OTHER CUSTOMIZATIONS:

N/A

**Comment by Pondaveia** [comment]
I can confirm this bug without testing since there's no event for Ouro to emerge:

https://github.com/azerothcore/azerothcore-wotlk/blob/master/src/server/scripts/Kalimdor/TempleOfAhnQiraj/boss_ouro.cpp#L66

Once I take care of my other bugs I'll remake The Temple of Ahn'Qiraj since most bosses are in need of a Re-vamp. They are still scripted with old timers. Feel free to report any bugs regarding the instance.

**Comment by BarbzYHOOL** [comment]
https://www.youtube.com/watch?v=MjxgppvcFrM video

**Comment by BarbzYHOOL** [comment]
I tried the dalaran core version and it didn't work at all either :D

**Comment by BarbzYHOOL** [comment]
Ouro is moving when spawned manually which seems weird.


This is one of the latest vanilla script version
https://github.com/vmangos/core/blob/development/src/scripts/kalimdor/silithus/temple_of_ahnqiraj/boss_ouro.cpp

**Comment by BarbzYHOOL** [comment]
The crash I reported above is not in our core, it's in a module.

The rest of the issue is still valid

**Comment by h0lysp4nk** [comment]
Looks like the Ouro Spawner in AQ40 exists but doesn't have any scripts or SAI attached to it whatsoever. TrinityCore/Mangos have the same issue. I'll take a look at implementing a fix :)

**Comment by BarbzYHOOL** [comment]
omg sorry i had identified these issues but forgot to post them


Of course, need to resolve the spawning, btw have you checked the link I put above?

And I also showed this issue to @AsunaFrostwyrm so I'm tagging him here to voice his opinion on whether you should do it, collaborate together or focus on one part of AQ (or even check BWL as it's bugged as hell) :)

**Comment by h0lysp4nk** [comment]
Okay not a problem, I'll wait to hear from him. I'll take a look at BWL in the meantime :)

**Comment by h0lysp4nk** [comment]
Resolved in my PR https://github.com/azerothcore/azerothcore-wotlk/pull/2997 :)

**Comment by JamesGent** [comment]
Confirmed still an issue from my testing. There's an Ouro Spawner NPC which attacks you and can be attacked, and upon killing it nothing happened.

The Ouro spawner NPC in the database has no scripts/AI attached. This thread contains a PR that claims to fix it but unknown if it does.

https://github.com/azerothcore/azerothcore-wotlk/pull/2997

![Desktop 27-11-2020 17-33-34-53](https://user-images.githubusercontent.com/61194190/100473877-4cd40f80-30d7-11eb-8e02-6e7c6ebda90e.png)

**Comment by valens14** [comment]
I've got this fixed.  It'll be my first time doing a pull request so I'll try to get that right.

**Comment by Si1ker** [comment]
#9285 should have closed this.
