### ISSUE TITLE
[QUEST] Death's Challenge

### ISSUE THREAD

**Issue by EricksOliveira** [azerothcore/azerothcore-wotlk#1849]
##### SMALL DESCRIPTION:

Quest ID: 12733
It is not allowing the duel with the death knight.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

When picking up the Quest ID: 12733 is automatically released the Duel option with the 5 Death Knights!

##### CURRENT BEHAVIOUR:

When you get to Quest ID: 12733 the Duels with the 5 Death Knights is not activated!

##### STEPS TO REPRODUCE THE PROBLEM:

1. Create a Death Knight
2. Take the Death's Challenge quest ID 12733.
3. Try calling one of the Death Riders to the Duel!

##### BRANCH(ES):

master

##### AC HASH/COMMIT:

6131c9d789bddad01a4a6b76e0fc4f98fe6a7927

##### OPERATING SYSTEM:

Windows 7

**Comment by poszer** [comment]
Are you sure? This is fixed some days ago 
https://github.com/azerothcore/azerothcore-wotlk/pull/1755

**Comment by Selyria** [comment]
Works problem-free the npc have just a countdown so you can not immediately challenge the same again 5-10 min believe 

https://youtu.be/bKMM5LifJRM

**Comment by EricksOliveira** [comment]
Yes. You still have the same problem! I just did the test again!

**Comment by poszer** [comment]
> Yes. You still have the same problem! I just did the test again!

There isn't problem with this. Create DK and try again

**Comment by EricksOliveira** [comment]
https://prntscr.com/nqiw46

**Comment by poszer** [comment]
> https://prntscr.com/nqiw46

First, you're testing it with GM char, with GM on -> Incorrect
Second, you have to test it with player account.
Third, complete previous quest required to open this one.
Done

**Comment by EricksOliveira** [comment]
https://prntscr.com/nqj4pr

Yes. You still have the same problem! I just did the test again! Account players and completed all previous quests! Anyone else with this problem or just me?

**Comment by poszer** [comment]
> https://prntscr.com/nqj4pr
> 
> Yes. You still have the same problem! I just did the test again! Account players and completed all previous quests! Anyone else with this problem or just me?

Did you apply this https://github.com/azerothcore/azerothcore-wotlk/commit/c05cea14b67ba142b6aa39d64cb09c5553e2aef8

**Comment by EricksOliveira** [comment]
Yes. Is applied

**Comment by poszer** [comment]
It's problem from your side (modifications). Just tested again, test is working on master, and there isn't problem with it.
![dk teste3](https://user-images.githubusercontent.com/41213210/57982977-c1db7900-7a4c-11e9-8121-76998f85bdb8.png)
![dkquest](https://user-images.githubusercontent.com/41213210/57982978-c1db7900-7a4c-11e9-9d77-35bbc4df81a6.png)
![dktest2](https://user-images.githubusercontent.com/41213210/57982979-c2740f80-7a4c-11e9-9639-79f873c329ed.png)
