### ISSUE TITLE
SendAreaTriggerMessage not fmt formatted

### ISSUE THREAD

**Issue by sogladev** [azerothcore/azerothcore-wotlk#20006]
### Current Behaviour

wrong format error message when trying to enter an instance "You must be at least level {} to enter."

![area_trigger](https://github.com/user-attachments/assets/c6a84ff5-42e6-423f-a52d-589bbf91532e)

### Expected Blizzlike Behaviour

{} should be 70 in this case

### Source

https://github.com/azerothcore/azerothcore-wotlk/blob/a196f7f28aa263dc7f9c532e15839f3b409fb68f/src/server/game/Handlers/MiscHandler.cpp#L691

likely this as well 

https://github.com/azerothcore/azerothcore-wotlk/blob/a196f7f28aa263dc7f9c532e15839f3b409fb68f/src/server/game/Handlers/MiscHandler.cpp#L708

### Steps to reproduce the problem

level <70
1. `.go xyz 3088 1375 185 530 4.6`
2. try to enter

### AC rev. hash/commit

a196f7f28aa2

### Operating system

ubuntu 24.04

**Comment by TheSCREWEDSoftware** [comment]
To add to the above.

Vanilla and TBC Dungeons and Raids have the message above.

WotLK Dungeons anr Raid show via chat the proper Level (and some raids even add "you need to be in a raid group").

**Comment by Kitzunu** [comment]
Easy fix. I can add it to my todo list of things for when I have time to fix it. Otherwise, just look at any of my previous commits

**Comment by kissingers** [comment]
Also there is many incomplete hpylink message at server.log, same as this, after the message change pr

2024-09-22 12:22:45 Player Horse GUID Full: 0x0000000000003f98 Type: Player Low: 16280 sent a message with an invalid link:
%.*s
2024-09-22 12:22:45 Player Harper GUID Full: 0x0000000000003fb3 Type: Player Low: 16307 sent a message with an invalid link:
%.*s
2024-09-22 12:22:45 Player Have GUID Full: 0x0000000000003f8f Type: Player Low: 16271 sent a message with an invalid link:
%.*s
2024-09-22 12:22:45 Player Hopeful GUID Full: 0x0000000000003fa1 Type: Player Low: 16289 sent a message with an invalid link:
%.*s

which at WorldSession.cpp  767 line

bool WorldSession::ValidateHyperlinksAndMaybeKick(std::string_view str)
{
    if (Acore::Hyperlinks::CheckAllLinks(str))
        return true;

    LOG_ERROR("network", "Player {} {} sent a message with an invalid link:\n%.*s", GetPlayer()->GetName(),
        GetPlayer()->GetGUID().ToString(), STRING_VIEW_FMT_ARG(str));

    if (sWorld->getIntConfig(CONFIG_CHAT_STRICT_LINK_CHECKING_KICK))
        KickPlayer("WorldSession::ValidateHyperlinksAndMaybeKick Invalid chat link");

    return false;
}

**Comment by TheSCREWEDSoftware** [comment]
Fixed in: https://github.com/azerothcore/mod-npc-talent-template/pull/50

**Comment by sogladev** [comment]
> Fixed in: [azerothcore/mod-npc-talent-template#50](https://github.com/azerothcore/mod-npc-talent-template/pull/50)  

The module PR did not fix this issue, it only referenced the issue because of the same formatting error shows in the module

**Comment by Kitzunu** [comment]
Must be fixed in core. But I am too swamped at work to have time to do it atm

**Comment by Exitare** [comment]
@Kitzunu, 
I tried to solve it on my own. 
I got it working by changing the {} with %s in the database. But as you mentioned this is not how you would fix it. 
Could you pinpoint me in the right direction regarding how you would fix it ?

Thank you

**Comment by Kitzunu** [comment]
We dont want to change anything in the DB as we want to use the fmt format

Here are some implementations I've done for it.

https://github.com/azerothcore/azerothcore-wotlk/pull/19491
https://github.com/azerothcore/azerothcore-wotlk/pull/19490
https://github.com/azerothcore/azerothcore-wotlk/pull/19449
https://github.com/azerothcore/azerothcore-wotlk/pull/19489
https://github.com/azerothcore/azerothcore-wotlk/pull/19718
