### ISSUE TITLE
[Class - Warrior] Sword Specialization doesn't proc with some melee abilities.

### ISSUE THREAD

**Issue by Rorschach91** [azerothcore/azerothcore-wotlk#20250]
Bug Triager Notes:

Original CC Reports:
1) https://github.com/chromiecraft/chromiecraft/issues/7398#issue-2568789056
2) https://github.com/chromiecraft/chromiecraft/issues/7399#issue-2568793751
3) https://github.com/chromiecraft/chromiecraft/issues/7400#issue-2568808346

It seems that [Sword Specialization](https://www.wowhead.com/wotlk/spell=12815/sword-specialization) talent doesn't proc if players use these melee abilities: [Hamstring](https://www.wowhead.com/wotlk/spell=25212/hamstring), [Sunder Armor](https://www.wowhead.com/wotlk/spell=11597/sunder-armor) and [Rend](https://github.com/chromiecraft/chromiecraft/issues/7400).

# What client do you play on?

enGB

### Faction

Alliance

### Content Phase:

Generic

### Current Behaviour

[Sunder Armor](https://www.wowhead.com/wotlk/spell=11597/sunder-armor) doesn't proc [Sudden Death](https://www.wowhead.com/wotlk/spell=29725/sudden-death), [Sword Specialization](https://www.wowhead.com/wotlk/spell=12815/sword-specialization)

### Expected Blizzlike Behaviour

It should

### Source

Don't have direct sources, but it is implied by existing implementation and spell description:

- [Sunder Armor](https://www.wowhead.com/wotlk/spell=11597/sunder-armor)  already procs [Mongoose](https://www.wowhead.com/wotlk/spell=28093/lightning-speed)
- [Rend](https://www.wowhead.com/wotlk/spell=6547/rend) procs [Sudden Death](https://www.wowhead.com/wotlk/spell=29725/sudden-death), [Mongoose](https://www.wowhead.com/wotlk/spell=28093/lightning-speed)
- both [Rend](https://www.wowhead.com/wotlk/spell=6547/rend) and  [Sunder Armor](https://www.wowhead.com/wotlk/spell=11597/sunder-armor) have the same Spell flags:
![image](https://github.com/user-attachments/assets/444b3af3-7dcc-43a1-aa14-d513974b5866)
- both [Sudden Death ](https://www.wowhead.com/wotlk/spell=29725/sudden-death)and [Sword Spec](https://www.wowhead.com/wotlk/spell=12815/sword-specialization) have the same description of hitting a target with a weapon, while [Rend](https://www.wowhead.com/wotlk/spell=6547/rend) says "Requires melee weapon"

### Steps to reproduce the problem

0. .mod hp 2000000
1. Spam macro till full rage
/target Asdx
.cooldown
/targetlasttarget
/cast Bloodrage

2. Go to target dummy and spam till out of rage
/stopattack
/cast Sunder Armor
/stopattack

3. Go to Step 1
4. Check log/damage meter(some white hits will slip, but you can see on logs it wasnt a Sword Spec proc)

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/529e9140323edeef916bd6a1b6c97e13aa38db08

### Operating system

Ubuntu 22.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-BreakingNewsOverride](https://github.com/AnchyDev/BreakingNewsOverride)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by Nyeriah** [comment]
ROBOT.TXT

Ignore bounties with attached closed issues.
NO BOUNTY HERE! IT HAS BEEN FIXED ALREADY.

**Comment by bonfax4** [comment]
> ROBOT.TXT
> 
> Ignore bounties with attached closed issues. NO BOUNTY HERE! IT HAS BEEN FIXED ALREADY.

It wasn't fixed tbf but that's a good thing. From what I'm reading in EJ sudden death should not proc from nondamaging abilities anyway. Unsure about sword spec

Edit: However wotlksims has sunder proccing both so i dunno.

Discussion [here](https://web.archive.org/web/20100626024922/http://elitistjerks.com/f81/t52872-simulationcraft_s_t_imulating_your_inner_rage/p3/) seems to imply it shouldnt
