### ISSUE TITLE
Client freezes after recent update (possible regression from latest commits)

### ISSUE THREAD

**Issue by r0m1ntik** [azerothcore/azerothcore-wotlk#23116]
### Current Behaviour

After applying the latest update, many players (and myself) experienced a complete client freeze — the game becomes unresponsive and can only be closed via Task Manager.
I am not entirely sure how to reproduce it consistently, but it happened shortly after deploying the new core update.
Since these are the only commits recently applied that could affect it, I believe one of them introduced the issue.
The server had around 1000 players online during the incident.

I reverted both commits and the issue disappeared.

Commits possibly related:

https://github.com/azerothcore/azerothcore-wotlk/commit/86af3f302b2b1e464661ef4e80eb049f58738ccc
 (possibly unrelated, reverted for safety)

https://github.com/azerothcore/azerothcore-wotlk/commit/b80353d2887a41299d27f51a13108f18eb00e118
 (most likely related to the problem)

### Expected Behaviour

Client should not freeze; game should remain stable and responsive after the update.

### Source

No direct source; issue observed after applying recent commits.

### Steps to reproduce the problem

1. Update core including the commits above.
2. Run the server under heavy player load (~1000 online).
3. Wait for some time during gameplay — client eventually freezes.
4. Revert commits → issue disappears.

### Extra Notes

Happens randomly, not tied to a specific zone or spell. Could be threading or packet-handling related.

### AC rev. hash/commit

https://github.com/azerothcore/azerothcore-wotlk/commit/2afcd037c7a8fcef6d330c59b8bc4bc8a17a86d2
<img width="1027" height="692" alt="Image" src="https://github.com/user-attachments/assets/84c1f11f-6ac6-4813-b73c-206843a5e5fd" />

<img width="938" height="312" alt="Image" src="https://github.com/user-attachments/assets/0683c753-c0b3-4aff-ac01-52e86acdc764" /> 

### Operating system

Debian 12

### Custom changes or Modules

Cfbg
Transmog
Skeleton

**Comment by Nyeriah** [comment]
cc @killerwife

**Comment by killerwife** [comment]
Cheers, gonna check smth and offer quick triage.

**Comment by killerwife** [comment]
Linked a PR which is meant to start triage of this.

**Comment by digz6666** [comment]
I have same issue.

**Comment by killerwife** [comment]
https://github.com/azerothcore/azerothcore-wotlk/pull/23147

Second pr as part of this issue

Also start posting client crash (has to be unmodded)

**Comment by killerwife** [comment]
Just to clear up some info

My Pr should address the issues that are at play but without client crash, packetlog or reproduction locally i cant myself validate stuff much further

**Comment by Francesco-Borzi** [comment]
@r0m1ntik @digz6666 please try the following: https://github.com/azerothcore/azerothcore-wotlk/pull/23147

that should solve the issue. If that is not the case, please provide detailed reproduction steps so @killerwife can fix it.

**Comment by FrancescoBorzi** [comment]
Closing this as apparently fixed by https://github.com/azerothcore/azerothcore-wotlk/pull/23147

If that is not the case, please let us know.

**Comment by siriusty1** [comment]
> Closing this as apparently fixed by [#23147](https://github.com/azerothcore/azerothcore-wotlk/pull/23147)
> 
> If that is not the case, please let us know.

still have problem, issue:https://github.com/azerothcore/azerothcore-wotlk/issues/23305

**Comment by tim3126** [comment]
Both spell=35011 and spell=51491 will cause this problem. Players will also be disconnected
