### ISSUE TITLE
Stranglethorn Fishing Extravaganza

### ISSUE THREAD

**Issue by FrancescoBorzi** [azerothcore/azerothcore-wotlk#4066]
Original report by @JamesGent 

##### SMALL DESCRIPTION:

STV Fishing Extravaganza not working as intended from my experience.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

NPCs spawn (working)
2pm fishing tourney is announced (working)
All schools become tastyfish schools (not working)
Someone hands in 40 fish and wins (also a second place prize)

##### CURRENT BEHAVIOUR:

The schools do not become Tastyfish Schools.

https://classic.wowhead.com/object=180248/school-of-tastyfish

https://classic.wowhead.com/guides/wow-classic-stranglethorn-vale-fishing-extravaganza

##### STEPS TO REPRODUCE THE PROBLEM:

1. Wait until 2pm next Sunday
2. See if the schools are tastyfish schools
3. Cry

##### AC HASH/COMMIT:

https://github.com/azerothcore/azerothcore-wotlk/commit/672057316a51

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by FrancescoBorzi** [comment]
@LukasVolgger there was a report here https://github.com/azerothcore/azerothcore-wotlk/issues/2404 which is now closed. However, according to @JamesGent , the issue is still there.

**Comment by Wowhungarian** [comment]
Same as Kalu'ak Fishing Derby. All of them should be fixed. They are important parts of the game.

**Comment by Yehonal** [comment]
https://github.com/azerothcore/azerothcore-wotlk/pull/2463

This pull request can be related but probably it doesn't fix the issue for all cases

**Comment by wizzymore** [comment]
Hi,

I don't see any problem with the event.
This:
> All schools become tastyfish schools (not working)

Is not true, the schools appear on random points on the map and i can confirm they are working.
![image](https://user-images.githubusercontent.com/25827787/103176571-81282080-487b-11eb-83b4-b4a2c9d948ef.png)
![image](https://user-images.githubusercontent.com/25827787/103176575-8b4a1f00-487b-11eb-9203-f1f1317d5722.png)
This is with the event started manually ( .event start 15 )

![image](https://user-images.githubusercontent.com/25827787/103176608-d06e5100-487b-11eb-916f-29915d11cf9e.png)

I can even confirm they drop:
![image](https://user-images.githubusercontent.com/25827787/103176641-1cb99100-487c-11eb-8952-d8607c599252.png)
( I even got the 0.1% chance green fish to drop, this one will taste good on the grill xD )

**Comment by wizzymore** [comment]
There are a total of 52 pools from which you can fish.
```sql
SELECT * FROM game_event_gameobject WHERE evententry = 15
```
Instead of this: 164445, all are the fishing pools needed for this event.

**Comment by wizzymore** [comment]
Also, some random funny stuff that i just discovered, after i tested all schools and collected 40 fish, i selected the Hook of the Master Angler and seems like this item is completely bugged, you click on it it gets consumed and you don't transform into a fish..

**Comment by JamesGent** [comment]
The wiki says;

> After this announcement, the majority of fish caught in fishing pools will be tastyfish, but rarely players may catch non-contest fish

other sources say the tastyfish are 80%+ droprate during the event.

I fished for 45 minutes (until a server restart) and caught over 300 fish/boxes in/around STV and got zero Tastyfish on Chromiecraft.

Something is definitely off even if some things are technically working.

Perhaps the bug is that Tastyfish can ONLY be caught from the 52 pools that spawn?

**Comment by wizzymore** [comment]
Hi, yes, "Perhaps the bug is that Tastyfish can ONLY be caught from the 52 pools that spawn?" this is right, you can only catch them from the pools.
This is written as well in the fishing tournament rules as well:
![image](https://user-images.githubusercontent.com/25827787/103177161-a53a3080-4880-11eb-9b7e-4a60df478126.png)

**Comment by JamesGent** [comment]
Here’s the hidden vital patch note change which renders my report technically not correct.

 Patch 5.1.0 (2012-11-27): Now caught from any pool in Stranglethorn Vale during the event. 
Previously only found in event-specific Tastyfish schools

I stand by that something is still funky on ChromieCraft if I can spend an hour fishing from pools all over STV and I didn’t find a single TastyFish pool or a single tastyfish.

I completed the event dozens of times on retail and T-core without issue so I don’t know what to say.

maybe it was just broken because it was the first one to trigger whereas you triggered it manually?

**Comment by wizzymore** [comment]
No, i triggered it in both ways by chaging the event time in the DB.

Also, .event start is the same as the automatic trigger.
Keep in mind 52 spawn on that huge map makes the fishing pool rare so you have to stay a little to find them, also, there is not a single pool in Booty Bay ( intended behaviour ).
Some close pools you can find are by my location, here are 3 pools at a relative close position ( maybe 100 yards between them )
![image](https://user-images.githubusercontent.com/25827787/103178125-c010a300-4888-11eb-9448-b5e3491598e3.png)

**Comment by JamesGent** [comment]
So. It's that time of week again. I think this needs to be reopened. I've tried for two weeks to do this event on ChromieCraft and I haven't been able to do it. I'm an experienced user who has done this event on retail, following guides, so a normal/inexperienced player would have no hope.

I am again at the fishing tournament without a single node to fish. I'm following guides written pre-2010 

http://www.wowlevelingaddons.com/winning-the-stranglethorn-vale-fishing-extravaganza/

https://xpoff.com/threads/help-with-stv-fishing-tournament.2813/page-2

Once again my rotation was North Coast + Yojamba Isle + Gurubashi Arena Coast.

https://classic.wowhead.com/item=19807/speckled-tastyfish

![Desktop 03-01-2021 14-04-20-138](https://user-images.githubusercontent.com/61194190/103480484-9a295800-4dcc-11eb-8c16-7714be72c8c9.png)

Here you can see me standing on Yojamba Isle (the most popular spot with the most nodes according to 2009-2010 guides) with Find Fish active and not a single node on the map. I have not been able to find a single Tastyfish node in 2 weeks.

I don't doubt that there are some pools in the zone somewhere, but the level cap is 19 so I can't risk getting close to any mobs. This should be achievable in our bracket considering every twink guide recommends its rewards as Best in Slot items.

![image](https://user-images.githubusercontent.com/61194190/103480564-00ae7600-4dcd-11eb-8f7f-e43d497a07c9.png)

**Comment by wizzymore** [comment]
Hi @JamesGent,

The event lasts 2 hours, also the turn in's last for 3 hours, as specified here, this is correct:
https://classic.wowhead.com/guides/wow-classic-stranglethorn-vale-fishing-extravaganza

What is not correct is the time they start, the start at 15:00 every sunday instead of 14:00 every sunday.

One more think i should let you know, i played classic and i participated in this event, if you look on wowhead, you can see 154 spawns:
https://classic.wowhead.com/item=19807/speckled-tastyfish
But, i can guarantee you that the amount of pools that spawn is not 154 in any case xD Taking in account that in classic you don't have a mount at that level, usually the winner won in about 1 hour - 1 hour and 15 minutes.

**Comment by wizzymore** [comment]
@JamesGent here is a list of spawns that is approximative the same as on AC, keep in mind in AC they all spawn in the same time, so what you see is what you get:
https://tbcdb.com/?object=180248

**Comment by JamesGent** [comment]
The event should run from 2 til 4 as it says on the ingame Calendar and many sources. The NPCs should hang around an extra hour.

As is, the event and NPCs all leave at 3pm, which is 1 hour after the 2pm start.

I think Wowhead's Classic DB and fishing/twink guides written/published in 2008-2009 are more reliable than TBCDB. Yojamba Isle should definitely have some spawns. 

Here's more sources from 2007-2009 that state Yojamba spawns Speckled.

https://www.ownedcore.com/forums/world-of-warcraft/world-of-warcraft-guides/14807-how-get-lucky-fishing-hat-twinks.html

https://vanillawowdb.com/?quest=8221

https://greentintedgoggles.wordpress.com/2010/07/27/lucky-fishing-hat/

**Comment by JamesGent** [comment]
It's that time of week again.

It is 1PM server time and the Schools of Tastyfish are on the map, the NPCs are spawned, and the event has begun 1 hour early.

This is why the events have been ending 1-2 hours early as well, most likely.

It should be;

NPCs spawn and event announced 2pm Server Time.

2 hours of Tastyfish fishing from 2pm til 4pm.

NPCs do not despawn until 5pm.

It currently is;

NPCs spawn at 1pm server time.

2 hours of Tastyfish fishing from 1pm til 3pm.

Event announced at 2pm.

NPCs despawn at 3pm.

![image](https://user-images.githubusercontent.com/61194190/104123675-89d12a00-5344-11eb-937e-5c92ac923e92.png)


- Grass.

**Comment by JamesGent** [comment]
People on the Chromie server are beginning to encounter and discuss these problems. It's time to assign this to someone!

![image](https://user-images.githubusercontent.com/61194190/107149475-adda5800-6950-11eb-9c72-d0f05d4a5b62.png)

**Comment by FateDestinyLife** [comment]
The event is broken in the new edition.

**Comment by sudlud** [comment]
#18207
