### ISSUE TITLE
pathfinding issue Scarlet Friar | Trisfal Glades [$10]

### ISSUE THREAD

**Issue by locus313** [azerothcore/azerothcore-wotlk#4435]
Original report:
https://github.com/chromiecraft/chromiecraft/issues/32  

##### CURRENT BEHAVIOUR:

looks like there is a pathfinding issue when you try to attack the scarlet friar on the back side of the tower

##### EXPECTED BLIZZLIKE BEHAVIOUR:

the scarlet friar should enter combat and attack you.

##### STEPS TO REPRODUCE THE PROBLEM:

1. .go xyz 2169.060057 -520.564026 81.634026
2. Try to hit the scarlet friar with spells from distance

video provide by original reporter:
https://youtu.be/Q7fGJsJYFM8

##### EXTRA NOTES:

Also confirmed this on commit https://github.com/azerothcore/azerothcore-wotlk/commit/0d52b4ca4a7ec2d8219c606b581f874186f171f9

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/b905ce8c354b7cfac899ac3ab67209d2995b4de2

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by FrancescoBorzi** [comment]
it's worth trying it on latest master, and see if it's still an issue (after the big Pathfinding improvements)

**Comment by Zoidwaffle** [comment]
Please add a map reference as well for coordinates - I ended up under the world somewhere :grin: 

`.go xyz 2169.060057 -520.564026 81.634026 0` works.

Seems like the exact spawning points for friars is randomized to some extend... I use a server with the c8f43d85849c40e08d0da38913489426a0c35388 (pathfinding commit) included. But I did find a friar where evading seems a bit excessive... I had a clear path between us, but it kept evading whan I was casting shadowbolts at it.

![WoWScrnShot_020421_154050](https://user-images.githubusercontent.com/541438/106909098-3ca46600-6700-11eb-9fb8-16defafc914a.jpg)

The screenshot was unable to capture the epic event, so you just have to take my word for it. It was all rank 1 shadowbolts and a friar resetting/evading every 2nd cast or so.

**Comment by BarbzYHOOL** [comment]
that outfit is sick on a tauren, zoid

**Comment by Zoidwaffle** [comment]
Yes... it's...
[puts on sunglasses]
terribull
[audience boos]

**Comment by FrancescoBorzi** [comment]
is this still an issue? cc @Yehonal

**Comment by Stifler82** [comment]
> is this still an issue? cc @Yehonal

Yes, it still is...

**Comment by Stifler82** [comment]
https://github.com/azerothcore/azerothcore-wotlk/issues/5022
https://github.com/chromiecraft/chromiecraft/issues/303

**Comment by UltraNix** [comment]
Cannot reproduce it - maybe already fixed by.. something :)

**Comment by Stifler82** [comment]
> Cannot reproduce it - maybe already fixed by.. something :)

It is STILL a problem and I'm able to reproduce it..


https://user-images.githubusercontent.com/1884642/113484588-05a0c580-94a1-11eb-83de-df818bbb44a8.mp4

**Comment by UltraNix** [comment]
Yep - I forgot about the mmaps folder :)

**Comment by Stifler82** [comment]
@UltraNix 
This is still a problem..
**Video Test:** [Vmaps-Pathfinding](https://youtu.be/3RtrpIyF1NQ)

**Comment by UltraNix** [comment]
Yep.

**Comment by Stifler82** [comment]
> Yep.

@UltraNix 
Btw, Great Job with LOS! 🚀🚀🚀
