### ISSUE TITLE
Various mobs in Tirisfal hitting in melee from several yards away

### ISSUE THREAD

**Issue by 55Honey** [azerothcore/azerothcore-wotlk#4673]
##### ISSUE: FACTION SIDE:

![Alliance](https://user-images.githubusercontent.com/1884642/108204869-3a88d100-711c-11eb-8179-e1b9b73ed450.png)
![Horde](https://user-images.githubusercontent.com/1884642/108204991-63a96180-711c-11eb-9ed9-138c233070a6.png)

##### CONTENT PHASE:

1-19

##### SMALL DESCRIPTION:

Mobs are hitting in melee from really far away (max distance frost bolt is 30 yards and they will melee hit me right after I engage with them).
NPC: [Rattlecage Soldier](https://classic.wowhead.com/npc=1520/rattlecage-soldier)
NPC: [Thurman Agamand](https://classic.wowhead.com/npc=1656/thurman-agamand)
NPC: [Nissa Agamand](https://classic.wowhead.com/npc=1655/nissa-agamand)
NPC: [Gregor Agamand](https://classic.wowhead.com/npc=1654/gregor-agamand)

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Mobs that rely on melee damage should not be able to hit a character until they are within melee range.

##### CURRENT BEHAVIOUR:

I noticed this while fighting Rattlecage Soldiers. When I open with a frostbolt on them, I enter combat and immediately get hit in melee twice despite being 30 yards away. You can see in the below screenshot my scrolling combat text from the default ui is "Entering Combat" and my log shows the -7 and -8 as melee swings even though the target is super far away.

![longest reach ever](https://user-images.githubusercontent.com/78349628/109456429-71b18900-7a1e-11eb-9c82-b912532fc66b.png)

I noticed similar behavior from Thurman Agamand, Gregor Agamand, and Nissa Agamand (who was hitting as I was kiting her within the house, so not quite from as far of a distance, but still too far).

##### STEPS TO REPRODUCE THE PROBLEM:

Step 1. Go to Agamand Mills in Tirisfal as anything with a ranged attack. 
Step 2. Attack one of the named mobs above from max distance.
Step 3. See if your combat log shows you taking any damage from melee attacks.

related: https://github.com/chromiecraft/chromiecraft/issues/115

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/c2f274e06dcf85c6ccc0ab282dd6f23e8ce49c8f

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by FrancescoBorzi** [comment]
thanks @55Honey , don't forget to set the label and the project ;)

**Comment by 55Honey** [comment]
> thanks @55Honey , don't forget to set the label and the project ;)

My Bad :)

**Comment by CameronWoof** [comment]
I'd like to add this exact issue with Foreststrider Fledglings in Darkshore--another creature with thrash.

**Comment by Knindzagxg** [comment]
That's really wierd.
Trash is 2x Extra Attacks but only while in melee range.

**Comment by Sathrenor** [comment]
Same case with [Blackwood Pathfinder](https://classic.wowhead.com/npc=2167/blackwood-pathfinder). Mobs can execute said skill from afar, but in my case I noticed it happens only after they cast an initial spell, but not when I was running away. _Although I could've missed it_

[Look at combat log](https://www.youtube.com/watch?v=deVcndbmuPA)
_As You can see Pathfinder managed to land a [Thrash](https://classic.wowhead.com/spell=3391/thrash) skill attack despite not being in melee range._

**Comment by CameronWoof** [comment]
Why was this marked as invalid? Surely this isn't intended?

**Comment by Stifler82** [comment]
https://user-images.githubusercontent.com/1884642/110249900-7a4f1580-7f70-11eb-81cf-342f62541c78.mp4

**Comment by CameronWoof** [comment]
Right--this video confirms that Thrash is bugged. It should be melee range.

**Comment by Stifler82** [comment]
> Right--this video confirms that Thrash is bugged. It should be melee range.

And **I want to clarify**, I'm not saying you're wrong, **just as I'm not saying you're right** either.
And through internal politics, **I am also forced to point out** that in the video **I am not telling you that YOU are arrogant**, I said that **what you said is arrogant**, **(and there is a big difference)**.

**Video:** [Prejudices](https://youtu.be/nnTXrSqxD4k)

**Comment by CameronWoof** [comment]
I watched your video, and I don't think it changes my position that melee enemies hitting from these distances is _clearly_ unintentional behavior. This isn't down to proof or documentation--common sense demands that an enemy with no way of striking from a distance (like a bow, or spells) should not be able to attack you from that range.

The only thing that strikes me as arrogant in this thread is your video. It's a lot of condescending talk with no explanation as to why you think it makes sense for birds to be able to hit someone from 30+ yards away.

**Comment by JamesGent** [comment]
You are correct that the issue is with the thrash spell (not the NPC) but the issue still remains in-game for many mobs so I'm reopening the issue.

All examples of Thrash ability are melee attacks with a self to 0 to 7 yard range. Thrash shouldn't be hitting people at range. Melee enemies don't become ranged by using Thrash (a melee ability).

https://wotlk.evowow.com/?search=thrash#npc-abilities

This may be an issue with "thrash stacking". Mobs with thrash will build up and save stacks of thrash until you return to melee, then they unleash all their thrashes at once. Maybe it's trying to thrash stack but instead attacks.

https://redd.it/d5dyoy

According to classic wowhead database the NPC shouldn't even have thrash. 

https://classic.wowhead.com/npc=1520/rattlecage-soldier#abilities

We're not 100% sure what the issue is but we're thankful to CameronWoof for raising the issue and hopefully we can work to fix it without getting side-tracked.

**Comment by Stifler82** [comment]
> I watched your video, and I don't think it changes my position that melee enemies hitting from these distances is _clearly_ unintentional behavior. This isn't down to proof or documentation--common sense demands that an enemy with no way of striking from a distance (like a bow, or spells) should not be able to attack you from that range.
> 
> The only thing that strikes me as arrogant in this thread is your video. It's a lot of condescending talk with no explanation as to why you think it makes sense for birds to be able to hit someone from 30+ yards away.

@CameronWoof
So, I realize that since English is not my language, and Italian is not your language, there may be a linguistic misunderstanding due to different ways of saying or the way of expressing oneself, therefore a problem of a cultural nature..

I tried to explain to you that:
**1 -** I did not say that YOU **(as a person)** are an arrogant person, INSTEAD I said, that: **(your statement was arrogant)** and **I also** expressed **the concept** that for me there is a **BIG** difference between the two things.
Because a person can also be a humble person, but sometimes come up with an arrogant phrase (maybe a little thoughtful phrase).
[Quote]: **"We are all human after all"** (if I'm not mistaken), so I guess we all get it wrong, or think little about an answer, don't we?


**2 -** I also said that I didn't know, if you were right or wrong, because there is no **"Documentation"** on internet regarding this Spell.
So I didn't say the Spell Thrash (It wasn't buggy), as I didn't say the opposite either.


**3 -** I put the Report as Invalid, because I wanted to take some time to check if the Spell was buggy or not.
And I did this, because I was afraid that someone with "Easy Click" would modify the spell before I investigated on it.

In fact...
-
I was right! 
Did you want proofs?
Here they are...
**Video:** [Trash](https://youtu.be/rPxyoncKLWs)
I agreed with you that a "Melee Spell" shouldn't hit from the distance, but I wanted to investigate that ID better, before anyone did any damage! (obviously without doing it on purpose).

Anyway... (various controversies aside), I figured out how to solve the problem, now I'll start working on it immediately, and I'll try to solve this problem as soon as possible..

And always remember that I never talk just to talk, and I never take anything for granted, everything I do, I do it with pondering and leave nothing to chance.

**Comment by Stifler82** [comment]
@Cosmic-Cocoa

Fixed!
-
**Video Test:** [Various mobs in Tirisfal](https://youtu.be/mW6IqYpu02k)

**Comment by htc16** [comment]
This still happens to me, on rev cd6e0d7e0b78

![image](https://user-images.githubusercontent.com/58153179/220917917-9bec6093-fd90-42e1-82fb-13ea533619f8.png)

**Comment by htc16** [comment]
> You're within his melee range. If anything, his hitbox is too large. He doesn't use thresh, nothing to do with this issue.

Is this not a bug then?

**Comment by Nyeriah** [comment]
This issue is about mobs hitting from 50 yards + because thrash added auto attacks with infinite range, I fixed that here: https://github.com/azerothcore/azerothcore-wotlk/pull/13697

In your case, looking at the screenshot you presented, I don't see an issue. There could be an issue with his hitbox if anything, but nothing compared to what is reported here.

**Comment by htc16** [comment]
Ok!
