### ISSUE TITLE
Pattern: Raptor Hide Harness not learnable by alliance LW

### ISSUE THREAD

**Issue by necropola** [azerothcore/azerothcore-wotlk#4854]
Original report: https://github.com/chromiecraft/chromiecraft/issues/204 by @Hemingway1970
Please check also https://github.com/chromiecraft/chromiecraft/issues/204#issuecomment-799536398 and the suggested change
```
UPDATE item_template SET FlagsExtra=0 WHERE entry=13287;
```

##### ISSUE: FACTION SIDE:
![Alliance](https://user-images.githubusercontent.com/1884642/108204869-3a88d100-711c-11eb-8179-e1b9b73ed450.png)

##### CONTENT PHASE:
20-29

##### SMALL DESCRIPTION:

The [Pattern Raptor Hide Harness](https://classic.wowhead.com/item=13287/pattern-raptor-hide-harness) is not learnable by alliance LW

Patten is sold by [Tunkk](https://classic.wowhead.com/npc=2819/tunkk)

##### EXPECTED BLIZZLIKE BEHAVIOUR:
Pattern should be learnable by any Leatherworker with the proper skill level. 

##### CURRENT BEHAVIOUR:
Recipe is not learnable by alliance LW and gives the error "You will never be able to use this item"

##### STEPS TO REPRODUCE THE PROBLEM:

Step 1 Obtain pattern on skilled alliance Leatherworker either by in game mail or by AH
Step 2 Attempt to learn pattern
Step 3 

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/a32310772487a7a547b1a239dfaf0967b19f7493

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by Zoidwaffle** [comment]
You can see all the flags here: https://www.azerothcore.org/wiki/item_template#flagsextra

So you are right, just change the `FlagsExtra` to 0.

If you just add backticks, it's fine.

```
UPDATE `item_template` SET `FlagsExtra`=0 WHERE `entry`=13287;
```

Could you make a PR for this change?

**Comment by necropola** [comment]
Sure. Gonan try my best to make a proper PR.

**Comment by necropola** [comment]
Done. Hope I did it correctly.
I wasn't able to actually link the issue to the PR. I've just mentioned it in the PR.

While testing I also noticed that **TC** has set both flags in their DB
* TC Harness pattern has FlagsExtra=1 (Horde-only)
* TC Belt patern has FlagsExtra=2 (Alliance-only)

This is at least consistent, though I still think it's wrong.

**Comment by Stifler82** [comment]
> Done. Hope I did it correctly.
> I wasn't able to actually link the issue to the PR. I've just mentioned it in the PR.
> 
> While testing I also noticed that **TC** has set both flags in their DB
> 
> * TC Harness pattern has FlagsExtra=1 (Horde-only)
> * TC Belt patern has FlagsExtra=2 (Alliance-only)
> 
> This is at least consistent, though I still think it's wrong.

@necropola 
you forgot to enter the CC report link
- Closes CC Link
- Closes AC Link

**Comment by necropola** [comment]
@Stifler82 
I already had
```
## Issues Addressed:
- Closes AzerothCore issue #4854
```
and I've now added
```
- Closes ChromieCraft issue https://github.com/chromiecraft/chromiecraft/issues/204
```

Is it now correct or am I still doing it wrong?

**Comment by Stifler82** [comment]
> @Stifler82
> I already had
> 
> ```
> ## Issues Addressed:
> - Closes AzerothCore issue #4854
> ```
> 
> and I've now added
> 
> ```
> - Closes ChromieCraft issue https://github.com/chromiecraft/chromiecraft/issues/204
> ```
> 
> Is it now correct or am I still doing it wrong?

@necropola 
it's perfect thanks, anyway (it's not relevant, you can do as you like), but you don't need to enter "- Closes AzerothCore issue" or "- Closes ChromieCraft issue"

just do:
- Closes + link
- Closes + link
