### ISSUE TITLE
.learn all my spells train incorrect spells.

### ISSUE THREAD

**Issue by walexaindre** [azerothcore/azerothcore-wotlk#5490]
## CURRENT BEHAVIOUR:

Command .learn all my spells or .learn all my class teaches wrong spells.

No talents and, "Burn out" learned.
https://i.imgur.com/Fw56dKN.jpg

Using .lookup spell burnout we can see that trained burnout with spell id 44450 is not a talent.

https://i.imgur.com/6ezoGwK.jpg

In a general sense, the spells learned do not correspond to those of the talents but are additional spells with the same name and apparently internal functionality.

It also happens with:

1. Living Bomb, Fireblast, Blizzard, Frostbite effect, Chilled effect, Water elemental (Prototype), Arcane Missiles.

2. Rogue Subtetly spells

3. Discipline priest spells, etc...

## STEPS TO REPRODUCE THE PROBLEM:

1.  Create a mage
2.  Use .learn all my spells or .learn all my class

## EXTRA NOTES:

This feature work in Trinity Core. The implementation is based in Trainers. 

## OPERATING SYSTEM:

Edition	Windows 10 Pro
Version	20H2
OS build	19042.928
Experience	Windows Feature Experience Pack 120.2212.551.0

## MODULES:

- [ X] Eluna Lua

- [ X]  CFBG

- [ X] Dynamic Xp

- [ X] Boss Announcer

## CUSTOMIZATIONS:

Delete uint16 limit for stats and uint8 for resistances.

**Comment by walexaindre** [comment]
Is there a web page that describes exactly each table and field in the database?

**Comment by r-o-b-o-t-o** [comment]
> Is there a web page that describes exactly each table and field in the database?

Hi, you could find some info on the wiki: https://www.azerothcore.org/wiki/database-world

**Comment by Kitzunu** [comment]
https://github.com/azerothcore/azerothcore-wotlk/pull/5428

Working on reworking trainers... Slow but steady

**Comment by TheSCREWEDSoftware** [comment]
I know this is an hold issue, but has been fixed throughout the years, when I don't know the rev. Check tested and working as intended, thanks for the report

**Comment by heyitsbench** [comment]
> Check tested and working as intended

This command still does not work as intended on a22403356c08ae21bdb2e7083fa1ae89c60523f0. Tested with Human Warrior, gave things like the talent Second Wind, two versions of Shattering Throw and Bloodthirst.

**Comment by Nyeriah** [comment]
The spell list is acquired by looking up the DBC, so each individual spell needs to be filtered before learn or removed after being learned. Fun

**Comment by TheSCREWEDSoftware** [comment]
> The spell list is acquired by looking up the DBC, so each individual spell needs to be filtered before learn or removed after being learned. Fun

This does mean we have to manually associate spells and talents to that then checks for the dbc for a match?

**Comment by Nyeriah** [comment]
No, we need to list the spells they shouldn't acquire and filter or remove them. If there's a criteria they all share it would be easier.

**Comment by TheSCREWEDSoftware** [comment]
> No, we need to list the spells they shouldn't acquire and filter or remove them. If there's a criteria they all share it would be easier. What comes to my mind is checking npc_trainer and only learning what is found in there. But that would exclude talents

Do you know by memory where this (the talents and spells) are being checked? curretnly

**Comment by Nyeriah** [comment]
https://github.com/azerothcore/azerothcore-wotlk/blob/master/src/server/scripts/Commands/cs_learn.cpp#L122
