### ISSUE TITLE
Darkmoon Faire - Incorrect Finishing Date

### ISSUE THREAD

**Issue by Azcobu** [azerothcore/azerothcore-wotlk#6345]
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [x] enUS
- [ ] other (specify)

##### FACTION

- [x] Alliance
- [x] Horde

##### CONTENT PHASE:

- [x] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

Original report: https://github.com/chromiecraft/chromiecraft/issues/858

On June 11h daily server restart at 5:30 server time, the DMF left Elwynn Forest when it was supposed to be in town until June 12th, 23:59.
I asked about it on discord but since no one answered, I did not know if it was worth a report.

Tester's notes: Messed about with my server clock and confirmed that the DMF will run until midnight 10th/11th of June, disappearing on the first server restart after that. Also set the clock back to just before the DMF is supposed to start on Sunday 6/6 at 12:01 AM , and found that it was starting at the correct time. 

Screenshot showing calendar claiming it is active, while the actual DMF site is empty. Current server date when this was taken was 11/6.
![WoWScrnShot_061421_141451](https://user-images.githubusercontent.com/81782124/121840489-8985f200-cd1b-11eb-9fea-31af0367ca5c.jpg)

Checking game_event table:
```
SELECT * from game_event WHERE evententry = 4;
```
```
+------------+---------------------+---------------------+-----------+--------+---------+--------------+--------------------------------+-------------+----------+
| eventEntry | start_time          | end_time            | occurence | length | holiday | holidayStage | description                    | world_event | announce |
+------------+---------------------+---------------------+-----------+--------+---------+--------------+--------------------------------+-------------+----------+
|          4 | 2014-09-07 08:31:00 | 2030-12-31 15:30:00 |    131040 |  10079 |     374 |            2 | Darkmoon Faire (Elwynn Forest) |           0 |        2 |
+------------+---------------------+---------------------+-----------+--------+---------+--------------+--------------------------------+-------------+----------+
```
Occurrence is minutes between event starts - 131040 minutes = 91 days.
Length is 10079 = 7 days less 1 minute.
Holiday is client side holiday ID - linked to holidays.dbc.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Accordng to Wowpedia, the DMF starts at 12:01 a.m. on the Sunday before the 1st Monday of each month and runs for a week. Thus it should end at 11:59 PM on Saturday the 12th.

Darkmoon Faire should be present according to the ingame calendar.

##### SOURCE:

https://wowpedia.fandom.com/wiki/Darkmoon_Faire_(Classic)?oldid=2411748

##### STEPS TO REPRODUCE THE PROBLEM:

1. Change server clock to some time after 12:01 AM on the 11th and before 11:59 PM on the 12th, when the DMF should be going, and start the server. Then visit Goldshire in Elwynn Forest (the DMF is a bit south of it) and note it's not there.

##### EXTRA NOTES:

Also note that TC are having the same problem: https://github.com/TrinityCore/TrinityCore/issues/25550

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/d0a52896283a9bfed36ca897f0c2ebe870a25800

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by Shineslippers** [comment]
https://github.com/chromiecraft/chromiecraft/issues/2746

I guess it's known, but will add anyway Mulgore -2 days and probably Terrokar -1 day due to same reason - leap years. As i mentioned in discord. We can do temporary fix by reschedule events `start_time` after 1 march of 2020. Up to 2024 it should work.

**Comment by UltraNix** [comment]
Done here #10068

**Comment by Stump876** [comment]
This is still an issue in Dun Morogh as of 9/20/22
![image](https://user-images.githubusercontent.com/68164076/191396858-78934dd7-fa3d-49bd-aa69-74faea507035.png)

**Comment by sudlud** [comment]
#24038
