### ISSUE TITLE
Mimiron P4 Laser Barrage

### ISSUE THREAD

**Issue by qwe900** [azerothcore/azerothcore-wotlk#8259]
### Current Behaviour

The Current bahavior of Leviathan and VX001 is wrong. 
Leviathan Stops 
VX001 is Spinnung up 4 Seconds in a fixxed pos not rdm.
VX001 doing Laserbarrage On a TARGET -wrong-
When laserbarage is done Leviathan follows tank again.

The problem is that the VX001 is a Passenger and has the ontransport flag and forced by code to the orientation of the Leviathan which should be disabled. I cant figure out how. 

### Expected Blizzlike Behaviour

Leviathan Stop
VX001 Spinning Up to a fixxed random Orientation.
Leviathan Move again.
VX001 Starts from the Fixxed Orientation and turn himself Clockwize even if Leviathan get Turnet by the Tank. He just follows his clockwize orientation until finish. We can set on periodic effect wtih setfacingto but the movement of Leviathan will brake all visuals while doing the Spell.

### Steps to reproduce the problem

gm on
go c 137630
gm off
cheat god on
start encounter
kill tank and head
see p4 behavior

### Extra Notes
is there someone who wants to fix that ecounter completly with me in Discord ?
I have already rewritten some stuff. 
https://www.mediafire.com/file/ggbzuxhqvwauehm/2021-10-04-13-02-52.mp4/file

_No response_

AzerothCore rev. 8c469d267a46 2021-10-04 13:51:53 +0000 (master branch) (Win64, Release, Static) 
Newest 

### Operating system

Windows X64

**Comment by FrancescoBorzi** [comment]
@qwe900 please include your AC version (commit hash)

**Comment by UltraNix** [comment]
@qwe900 Can you test https://github.com/azerothcore/azerothcore-wotlk/pull/8170? It should resolve that problems.

**Comment by qwe900** [comment]
> 
> 
> @qwe900 Can you test #8170? It should resolve that problems.

This does not fix the issue, the issue u fixxed is just the braking emotestate which is just because vx uses the wrong hovercode in the Main Repo. 

`UPDATE `acore_world`.`creature_template_addon` SET `bytes1` = 54432 WHERE `entry` = 33651`
For VX uses the correct hover

After Summoned has the correct emotestate:
`        npc_ulduar_vx001AI(Creature* pCreature) : ScriptedAI(pCreature)
        {
            pInstance  = me->GetInstanceScript();
            bIsEvading = false;
            me->SetUInt32Value(UNIT_NPC_EMOTESTATE, EMOTE_STATE_SPECIAL_UNARMED);
            me->SetDisableGravity(true);
        }`

And Edit Set Data on P1 start to :

`case 1:
                {

                    Unit* LMK2 = GetLMK2();
                    me->SetUInt32Value(UNIT_NPC_EMOTESTATE, EMOTE_ONESHOT_NONE);
                    me->RemoveFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_NOT_SELECTABLE);
                    me->CastSpell(LMK2, 64387); // is needed to do the correct animations on jump dont use Entervehicle
                }`

**Comment by UltraNix** [comment]
@qwe900 Please, read the fix again.

**Comment by boom8866** [comment]
Now it won't rotate at all

**Comment by Nyeriah** [comment]
Can no longer be reproduced
